baseURL = "http://meghprkh.github.io/blog/"
languageCode = "en-us"
title = "Megh's Blog"
theme = "mogra"
relativeURLS = true
canonifyurls = true

[params]
utterances = """
<script src="https://utteranc.es/client.js"
        repo="meghprkh/blog"
        issue-term="pathname"
        label="comments"
        theme="github-light"
        crossorigin="anonymous"
        async>
</script>
"""

[menu]

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Feed"
url = "/index.xml"
weight = 5
